services:
  nodecal:
    image: ghcr.io/gjessing1/nodecal:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - /mnt/data/nodecal/config:/config
      - /mnt/data/nodecal/cache:/cache
