services:
  nodecal:
    image: ghcr.io/gjessing1/nodecal:latest
    restart: unless-stopped
    ports:
      - '3042:3000'
    env_file: .env
    volumes:
      - type: bind
        source: /mnt/data/nodecal/config
        target: /config
        bind:
          create_host_path: false
      - type: bind
        source: /mnt/data/nodecal/cache
        target: /cache
        bind:
          create_host_path: false
